### ISSUE TITLE
Two Pointers Technique- find two numbers with a given sum in CPP

### ISSUE THREAD

**Issue by ChetasShree** [Lakhankumawat/LearnCPP#107]
### Description

Hi
I am a contributor at GSSOC'22, and I would like to contribute in CPP this problem statement, I will even add explanation and time comp and space comp and test cases.
Can you please assign this issue to me?

### Domain

Data Structure

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by wvaibhava** [comment]
I would like to contribute to this issue. I can approach the solution of this problem using two methods, 1)Hashmap 2) Two Pointer Approach with detailed explanation. 

Approach using Two Pointers:

1) This problem requires output pair of indices instead of pair of values, so we will take arrays, a to store their value with their respective indices.
2) We can sort array arr by their values.
3) Then we can use two-pointer, left point to the first element, right point to the last element (l=0,r=n-1). where n is the size of array.
