### ISSUE TITLE
Add two numbers represented by linked lists 

### ISSUE THREAD

**Issue by ashuraj15** [Lakhankumawat/LearnCPP#118]
### Description

Given two numbers represented by two linked lists and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

I would love to work on this as part of GSSoC'22.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by i-am-aisha** [comment]
Greetings sir!
I solved a lot of questions on  different types of data structures and linked list is my favourite one ,I can provide  the best solution of this issue (brute force approach as well as optimal approach) with proper comments with mentioning time complexity of every step so that one can easily get the approach without any difficulty.I am a GSSOC'22 contributor and I want to contribute in your project so please assign me this issue.
Thankyou!

**Comment by Poojaamangal** [comment]
@i-am-aisha kindly create  a new issue follow GSSoC guidline FCFS-FIRST COME FIRST SERVE .

**Comment by ashuraj15** [comment]
@Lakhankumawat As a part of GSSoC'22, Can you assign me this issue?
