### ISSUE TITLE
Swap nodes of linked list 

### ISSUE THREAD

**Issue by DlVYANSH** [Lakhankumawat/LearnCPP#125]
### Description

our program will swap two nodes of the linked list by changing the links( not by swapping the values )

Please assign this to me. I am also contributor in gssoc'22

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by i-am-aisha** [comment]
Description:
my program will pairwise swap elements of a given linked list in both iterative and recursive approach with time complexity-O(n) in both methods .  please assign to me this issue so that i can contribute in this project. I am a contributor in GSSOC'22.
 Domain:
Data structure and algorithms
Type of contribution:
Addition

**Comment by Lakhankumawat** [comment]
@Nanzzie  issue is assigned to you, you can start working on it because , @DlVYANSH  is already assigned other issue .

**Comment by Lakhankumawat** [comment]
Hey @DlVYANSH  , You can only create one issue at a time . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.
