### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by sauradip007** [Lakhankumawat/LearnCPP#175]
### Description

This is a sudoku solver implemented on a 9x9 board using backtracking

### Domain

CPP

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by chandan9369** [comment]
@sauradip007  please assign me this issue so that i start working on this issue.

**Comment by n4i9kita** [comment]
@sauradip007 please explain your approach in a more descriptive manner.

**Comment by Rashmisingh-18** [comment]
I want to work on this issue.
Descriptive Approach: In a Sudoku Solver, which works as follows: suppose we have a Sudoku grid and we have to solve the number maze problem, Sudoku. Since, Sudoku is a 9 x 9 number grid, the whole grid are also divided into 3 x 3 boxes 

There are some rules to solve the Sudoku.
* We have to use digits 1 to 9 for solving this problem.
* One digit cannot be repeated in one row, one column, or in one 3 x 3 box.
* To solve, try every configuration one by one until the correct configuration is found, i.e. for every unassigned position fill the 
   position with a number from 1 to 9. After filling all the unassigned positions check if the matrix is safe or not. If safe print else 
   recurs for other cases.

Please assign this to me @n4i9kita
