### ISSUE TITLE
Implementation of different sorting algorithms using CPP

### ISSUE THREAD

**Issue by salahashraf253** [Lakhankumawat/LearnCPP#240]
### Description

Description
there are many sorting algorithms with different time , space complexity .
I will implement counting sort and explain it's complexity . 

I am participating in gssoc'22. please assign this to me.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
You can only contribute one sorting algorithm at a time in one issue not many and it will be good for you to because once your PR is created you'll be able to create new issue for next sorting algorithm , having different prs will give you more points 

Edit your Desc. and come up with only one which is not present in repo and is not raised as an issue of other contributors.

**Comment by salahashraf253** [comment]
I have edit the description , can you check it now  ?
