### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by PeritusDeveloper** [Lakhankumawat/LearnCPP#243]
### Description

Non-Comparison Sorting Algorithms sort numbers without comparing them.
I would like to implement Counting Sort
Counting Sort is a stable algorithm which sorts elements using frequency count of each number.
The README file will also be updated for this algorithm

I am GSSoC 2022 Contributor.
@miraj0507 Can you assign me this issue?

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
You can only contribute one sorting algorithm at a time in one issue not many and it will be good for you to because once your PR is created you'll be able to create new issue for next sorting algorithm , having different prs will give you more points

Edit your Desc. and come up with only one which is not present in repo and is not raised as an issue of other contributors.

I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk), thanks.

**Comment by PeritusDeveloper** [comment]
I will implement Counting Sort first
Radix and Bucket Sort will be implemented in next issues after merging PR for counting sort

**Comment by miraj0507** [comment]
So kindly update the title as soon as possible, as Counting sort, I will be assigning you the issue.
