### ISSUE TITLE
[Adding] Middle element of the Singly LInked-list

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Lakhankumawat/LearnCPP#63]
Hey ,Greeting's of the day 
I want to add a new code file which calculates the middle element of the linked list .. to the repository  .i.e .
 
### LearnCPP/P-Problem Statements & Solution/1-Level 1/MiddleElement_Singly_LInkedlist.cpp
........
Plss assign this issue to me .. under  ###  **GSSOC'22** 

Thank's regard :crossed_fingers:

**Comment by Lakhankumawat** [comment]
hi  @Vikash-8090-Yadav  thanks for reaching out but problem statements are not accepted in this project as GSSOC'22 contribution cause anyone you know can copy a problem from leetcode , paste solution in PR and can create such PR's which won't be a valid contribution , you can see what are the issues in the accepted issues , they have a algorithm dedicated , so i recommend you come up with something else .


you can contribute this issue to the repo if you want to but it won't be counted in your point for GSSOC'22 but i recommend you contribute this issue instead of closing because you'll learn from it.

Happy Coding !!

**Comment by Vikash-8090-Yadav** [comment]
Ok. ...no issue.
Yes I will complete this when ever I get free from gssoc''22.
