### ISSUE TITLE
Pattern Searching using Finite Automata Algorithm

### ISSUE THREAD

**Issue by helix17** [Lakhankumawat/LearnCPP#71]
### Description

In Finite Automata algorithm, a Finite Automata is constructed in the form of a 2D array after the pattern is pre-processed. Once the Finite Automata in built, it can be traversed from the first state along with the input text for pattern recognition. The next state of the finite automata is decided by the next letter of the input text. The pattern is found if the 
the finite automata reaches the final state. 

@Lakhankumawat I'm a GSSoC 2022 participant. Please assign this issue to me.

### Domain

Algorithm

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

**Comment by Lakhankumawat** [comment]
hi @helix17  thanks for reaching out but problem statements are not accepted in this project as GSSOC'22 contribution cause anyone you know can copy a problem from leetcode , paste solution in PR and can create such PR's which won't be a valid contribution , you can see what are the issues in the accepted issues , they have a algorithm dedicated , so i recommend you come up with something else .

you can contribute this issue to the repo if you want to but it won't be counted in your point for GSSOC'22 but i recommend you contribute this issue instead of closing because you'll learn from it.

Happy Coding !!

**Comment by helix17** [comment]
> 

Thanks for letting me know. I'll look for another algorithm to work on along with this issue.

**Comment by helix17** [comment]
> hi @helix17 thanks for reaching out but problem statements are not accepted in this project as GSSOC'22 contribution cause anyone you know can copy a problem from leetcode , paste solution in PR and can create such PR's which won't be a valid contribution , you can see what are the issues in the accepted issues , they have a algorithm dedicated , so i recommend you come up with something else .
> 
> you can contribute this issue to the repo if you want to but it won't be counted in your point for GSSOC'22 but i recommend you contribute this issue instead of closing because you'll learn from it.
> 
> Happy Coding !!

Thanks for letting me know. I'll look for another algorithm to work on along with this issue.

**Comment by Lakhankumawat** [comment]
closing the issue
